POST http://localhost:3002/api/moves
content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp1dXVwYWp1dXQiLCJpZCI6IjVlMjdkZDVkN2M3OWViMTkxNGVjMGY1YyIsImlhdCI6MTU3OTY3MjQyNn0.PU2XhWRCpGGgG9b81dTQO8oX0-ZSQBZ5iSEIaryYOyY

{
  "name": "New move",
  "userId": "5e411a0ab3ad200004047be9"
}

  
  
  